### PR TITLE
Update jsonschema.lua (typo #51)

### PR DESCRIPTION
**Pull request by BobinMathew**

### CODE REVIEW

**Comment by membphis** [comment]
@BobinMathew you need to sign the `cla` first

image

**Comment by Yiyiyimu** [comment]
ping @BobinMathew

**Comment by membphis** [comment]
@Yiyiyimu would you like to handle this job?

**Comment by Yiyiyimu** [comment]
> Would you like to handle this job?

Got it

**Comment by membphis** [comment]
close this PR

**Pull request closed without merging**
