### PR TITLE
fix: endless loop in utf8_len while input is an invalid utf8 string

### LINKED ISSUE #61: endless loop in utf8_len
function validatorlib.utf8_len(s)
  local c, j=0, 1
  while j <= #s do
    local cb = str_byte(s, j)
    if cb >= 0 and cb <= 127 then j = j + 1
    elseif cb >= 192 and cb <= 223 then j = j + 2
    elseif cb >= 224 and cb <= 239 then j = j + 3
    elseif cb >= 240 and cb <= 247 then j = j + 4
    end
    c = c + 1
  end
  return c
end

input "%ff", after urldecode ，str_byte(s,j), when cb > 247，#s = 1, j = 1 , will cause endless loop

### PR DESCRIPTION
**Pull request by Gerrard-YNWA**
This pr references the implementation of the [`utf8.RuneCountInString`](https://github.com/golang/go/blob/master/src/unicode/utf8/utf8.go#L411) in golang, takes invalid utf8 strings in consideration and treats them as single bytes. close #61

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
@Gerrard-YNWA do you have time to resolve the confilicts? After this, we are ready to merge this PR

**Comment by Gerrard-YNWA** [comment]
@membphis  I have rebased the latest code but CI seems failed on install Linux Script step

**Comment by spacewander** [comment]
We can upgrade luarocks to 3.8.0 via this action?
https://github.com/leafo/gh-actions-luarocks

**Comment by Gerrard-YNWA** [comment]
> We can upgrade luarocks to 3.8.0 via this action? https://github.com/leafo/gh-actions-luarocks

Okay, I'll have a try.

**Comment by Gerrard-YNWA** [comment]
Hi @spacewander, CI passed now, plz take a look when you have time : )

**Review by membphis — APPROVED** [review]

**Comment by spacewander** [comment]
@Gerrard-YNWA 
Could you resolve the conflict?

**Comment by Gerrard-YNWA** [comment]
@spacewander resolved : )

**Review by spacewander — APPROVED** [review]

**Comment by spacewander** [comment]
Merged. Thanks!

**Pull request merged**
